[".oh-my-zsh"]
	type = "archive"
	url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
	exact = true
	stripComponents = 1
	refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/*.zsh", "*/.version", "*/.revision-hash", "*/highlighters/**"]
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/ys.zsh-theme"]
	type = "file"
    url = "https://raw.githubusercontent.com/sunrisewestern/zsh_theme/main/ys.zsh-theme"
    refreshPeriod = "672h"
[".vim/bundle/Vundle.vim"]
	type = "git-repo"
    url = "https://github.com/VundleVim/Vundle.vim.git"
    refreshPeriod = "168h"

{{ if eq .chezmoi.os "linux" -}}
{{ $ageVersion := "1.1.1" -}}
[".local/bin/age"]
    type = "file"
    url = "https://github.com/FiloSottile/age/releases/download/v{{ $ageVersion }}/age-v{{ $ageVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/age".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "age/age"]
{{ end -}}

{{ $lsdVersion := "1.1.2" -}}

{{ if eq .chezmoi.os "linux" -}}
{{ if eq .chezmoi.arch "amd64" -}}
[".local/bin/lsd"]
  type = "file"
  url = "https://github.com/lsd-rs/lsd/releases/download/v{{ $lsdVersion }}/lsd-v{{ $lsdVersion }}-i686-unknown-linux-musl.tar.gz"
  refreshPeriod = "168h"
  [".local/bin/lsd".filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lsd-v{{ $lsdVersion }}-i686-unknown-linux-musl/lsd"]
{{ end -}}

{{ if eq .chezmoi.arch "arm64" -}}
[".local/bin/lsd"]
  type = "file"
  url = "https://github.com/lsd-rs/lsd/releases/download/v{{ $lsdVersion }}/lsd-v{{ $lsdVersion }}-arm-unknown-linux-gnueabihf.tar.gz"
  refreshPeriod = "168h"
  [".local/bin/lsd".filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lsd-v{{ $lsdVersion }}-arm-unknown-linux-gnueabihf/lsd"]
{{ end -}}
{{ end -}}
