encryption = "age"
[age]
    identity = "~/key.txt"
    recipient = "age1xh83clm947tg7fljhm0c7c84nt699gjmqanc5y3e9vkacc6gys8sazs55q"

[git]
    autoCommit = true
    autoPush = false

[warnings]
    configFileTemplateHasChanged = false

